CONTRIBUTING.md
README.md
jest.config.js
src/client/theme/SearchBar/SearchBar.css

BREAKING CHANGE: css already included.

feat: shipped with css

---

src/client/theme/SearchBar/fetchIndexes.spec.ts
src/client/theme/SearchBar/fetchIndexes.ts
src/client/utils/SearchSourceFactory.spec.ts
src/client/utils/SearchSourceFactory.ts
src/client/utils/__mocks__/proxiedGenerated.ts
src/client/utils/smartQueries.spec.ts
src/client/utils/smartTerms.spec.ts
src/client/utils/smartTerms.ts
src/client/utils/tokenize.spec.ts
src/client/utils/tokenize.ts
src/declarations.ts
src/server/utils/buildIndex.spec.ts
src/server/utils/buildIndex.ts
src/server/utils/generate.spec.ts
src/server/utils/generate.ts

fix: fix languages other than en and zh

---

README.md
src/client/theme/SearchBar/EmptyTemplate.spec.ts
src/client/theme/SearchBar/EmptyTemplate.ts
src/client/theme/SearchBar/SearchBar.tsx
src/client/theme/SearchPage/SearchPage.tsx
src/client/utils/__mocks__/proxiedGenerated.ts
src/client/utils/simpleTemplate.spec.ts
src/client/utils/simpleTemplate.ts
src/declarations.ts
src/server/utils/generate.spec.ts
src/server/utils/generate.ts
src/server/utils/validateOptions.spec.ts
src/server/utils/validateOptions.ts
src/shared/interfaces.ts

feat: support translations in plugin options

---

src/client/theme/SearchPage/SearchPage.tsx

fix: remove form from search page

---

src/client/theme/SearchBar/SearchBar.tsx

fix: fix search bar error with new docusaurus

---

src/client/theme/SearchBar/SearchBar.tsx

fix(): support webpack v5 since docusaurus v2 alpha 75

---

src/client/theme/SearchBar/SearchBar.tsx

fix: fix an issue of highlighting in code blocks

---

src/client/theme/SearchPage/SearchPage.module.css

fix: fix input box style of search page in dark mode

---

src/client/theme/SearchBar/SearchBar.module.css

fix: refine styles with dark navbar

---

src/client/theme/SearchBar/SearchBar.module.css

fix: set max-width for dropdown on small screen

---

README.md
package.json
src/server/utils/tokenizer.spec.ts
src/server/utils/tokenizer.ts
yarn.lock

close https://github.com/easyops-cn/docusaurus-search-local/issues/140

feat: replace nodejieba with @node-rs/jieba

---

package.json
src/client/theme/SearchBar/SuggestionTemplate.ts
src/server/utils/parseDocument.spec.ts
src/server/utils/parseDocument.ts
yarn.lock

fix: fix indexing content between h1 and h2

---

docusaurus-search-local/src/client/theme/SearchBar/SearchBar.module.css
docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx

It will both clear the search bar and any active marks.

Added a clear button to the search bar

---

docusaurus-search-local/src/client/theme/SearchBar/SearchBar.module.css
docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx

fix: hide clear button on small screen when input is not focused

---

README.md
docusaurus-search-local/src/client/utils/highlightStemmed.spec.ts
docusaurus-search-local/src/client/utils/highlightStemmed.ts
docusaurus-search-local/src/client/utils/looseTokenize.ts
docusaurus-search-local/src/server/utils/getCondensedText.spec.ts
docusaurus-search-local/src/server/utils/getCondensedText.ts
docusaurus-search-local/src/shared/interfaces.ts

fix: fix call stack overflow with large code blocks

---

docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx
docusaurus-search-local/src/client/theme/SearchPage/SearchPage.tsx

Fixes #242 
Not sure if this is the best approach but it sure works

fix: use debug instead of console.error for useDocsPreferredVersion

---

docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx
docusaurus-search-local/src/client/theme/SearchPage/SearchPage.tsx
docusaurus-search-local/src/client/theme/hooks/useSearchQuery.ts

fix: pass version instead of detect version in search page

---

docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx
docusaurus-search-local/src/client/theme/hooks/useSearchQuery.ts

fix: fix SSR warning, closes #364

---

.eslintrc
docusaurus-search-local/src/server/utils/parse.spec.ts
docusaurus-search-local/src/server/utils/parse.ts
docusaurus-search-local/src/server/utils/scanDocuments.spec.ts
docusaurus-search-local/src/server/utils/scanDocuments.ts
website/docs/unlisted-post.md

feat: do not index unlisted content

---

docusaurus-search-local/locales/de.json

Adds JSON with German plugin translation.

feat: add German locale

---

docusaurus-search-local/src/client/theme/SearchPage/SearchPage.tsx

fix: fix search page no results, closes #389

---

docusaurus-search-local/src/client/theme/SearchBar/SuggestionTemplate.spec.ts
docusaurus-search-local/src/client/theme/SearchBar/SuggestionTemplate.ts
docusaurus-search-local/src/client/theme/SearchPage/SearchPage.tsx
docusaurus-search-local/src/client/utils/SearchSourceFactory.spec.ts
docusaurus-search-local/src/client/utils/SearchSourceFactory.ts
docusaurus-search-local/src/client/utils/processTreeStatusOfSearchResults.spec.ts
docusaurus-search-local/src/client/utils/processTreeStatusOfSearchResults.ts
docusaurus-search-local/src/client/utils/sortSearchResults.spec.ts
docusaurus-search-local/src/client/utils/sortSearchResults.ts
docusaurus-search-local/src/server/utils/parse.spec.ts
docusaurus-search-local/src/server/utils/parseDocument.spec.ts
docusaurus-search-local/src/server/utils/parseDocument.ts
docusaurus-search-local/src/server/utils/parsePage.spec.ts
docusaurus-search-local/src/server/utils/parsePage.ts
docusaurus-search-local/src/server/utils/scanDocuments.spec.ts
docusaurus-search-local/src/server/utils/scanDocuments.ts
docusaurus-search-local/src/shared/interfaces.ts
website/docs/intro.md

feat: support search based on description and keywords

---

README.md
docusaurus-search-local/locales/de.json
docusaurus-search-local/locales/vi.json
docusaurus-search-local/locales/zh-Hans.json
docusaurus-search-local/src/client/theme/SearchPage/SearchPage.tsx

Add `theme.SearchPage.searchContext.everywhere` to locales

feat(i18n): add `theme.SearchPage.searchContext.everywhere` to locales

---

.eslintrc
docusaurus-search-local/package.json
docusaurus-search-local/src/server/utils/getCondensedText.spec.ts
docusaurus-search-local/src/server/utils/parse.ts
docusaurus-search-local/src/server/utils/parseDocument.spec.ts
docusaurus-search-local/src/server/utils/parsePage.spec.ts
jest.config.js
jestSetup.js
package.json
yarn.lock

fix: update cheerio to 1.0.0

---

docusaurus-search-local/src/server/utils/generate.spec.ts
docusaurus-search-local/src/server/utils/generate.ts

fix: use `require.resolve` for generated js, fixes #459

---

docusaurus-search-local/src/server/utils/parseDocument.spec.ts
docusaurus-search-local/src/server/utils/parseDocument.ts

fix: handle keywords stemmer, fix #487
